/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../../../Library/Android/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_wu_ov_DemoActivity2 */

#ifndef _Included_com_wu_ov_DemoActivity2
#define _Included_com_wu_ov_DemoActivity2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wu_ov_DemoActivity2
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_wu_ov_DemoActivity2_getEdge
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
